name: Generate Readme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Combine files
        uses: technote-space/file-concat-action@v1
        with:
          files: |
            - https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/table-of-contents.md
            - https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/configure-pm2.md
          output: combined.md

      - name: Create readme file
        run: |
          mv combined.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update README file'
