name: Update README from RawContent URL
on:
  push:
    branches:
      - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install markdown-include
        run: npm install markdown-include@latest
      - name: Update README from markdown-include
        run: npx markdown-include README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update README from markdown-include"
          add: "README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
