name: Generate Readme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Combine files
        run: |
          toc=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/table-of-contents.md)
          config=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/configure-pm2.md)
          readme="${toc}${config}"
          echo "${readme}" > README.md

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto'
