name: Update README

on:
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Markdown-Include
        run: npm install -g markdown-include
      - name: Update README
        run: markdown-include README.md --replace --stdin < <(echo '<!-- markdown-include url="https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/README.md" -->')
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          message: Update README
          author_name: Your Name
          author_email: your_email@example.com
