name: Generate Readme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Combine files
        run: |
          toc=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/table-of-contents.md)
          config=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/configure-pm2.md)
          readme="${toc}${config}"
          echo "${readme}" > README.md

      - name: Commit changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --global user.name "Your Name"
            git config --global user.email "youremail@example.com"
            git add README.md
            git commit -m "Auto commit updated README.md"
            git push origin main
