name: Generate Readme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Combine files
        run: |
          toc=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/table-of-contents.md)
          config=$(curl -sS https://raw.githubusercontent.com/brettjrea/Debian_Generate_Readme/main/configure-pm2.md)
          readme="${toc}${config}"
          echo "${readme}" > README.md

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README file"
          git push origin main
